### ISSUE TITLE
Double Y axis

### ISSUE THREAD

**Issue by nikovrdoljak** [leighquince/Chart.js#10]
Hi,
I found your Overlay solution for mixing bar and line chart excellent, but I wonder do you plan to add support for additional Y axis; e.g. one for bar and another for line chart values?

**Comment by leighquince** [comment]
i had looked into this a while back and deiced i needed some time to come up with a proper implementation. So in answer yes but it won't be quick. I will keep this open as an enhancement and reply back here when i start making progress on it.

**Comment by leighquince** [comment]
its been a while but i am currently working on this now, i have a working prototype with the normal chartjs (have a look at branch with it on to see what has been done or some examples can be seen - https://github.com/nnnick/Chart.js/pull/1088) and currently now trying to merge that into my own fork but with all of my own changes it is not as simple as i though it would be so will still be a bit before this feature is fully present here. (i'd say at least a month)

**Comment by leptoquark1** [comment]
You got any progress on this issue?

**Comment by leighquince** [comment]
Sorry for this taking so long, i have finally finished a port from the prototype i wrote into this fork. i have tested that all old features are still working but if you use this and see any issues let me know. The latest on master has this feature
