### ISSUE TITLE
Target Line

### ISSUE THREAD

**Issue by jlien-calwater** [leighquince/Chart.js#11]
Is there a way to add a horizontal target line (non-connecting line graph)?

![image](https://cloud.githubusercontent.com/assets/3473846/7503818/336ac540-f3fa-11e4-8edd-e9d3f6170855.png)

**Comment by leighquince** [comment]
Hey sorry I never got back to you about this. In short there is no immediate way as even with using the overlay chart the line is just one point and starts in the middle of the bar groups so would not produce the required effect.

I would say this is a new chart type (no idea what it would be called) as it's quite specific
