### ISSUE TITLE
Is there a chance to port overlay as as chart.js plugin?

### ISSUE THREAD

**Issue by pikopl** [leighquince/Chart.js#14]
By now overlay functionality is available as fork of original Chart.js. Is there a chance to port it as chart.js plugin?

**Comment by leighquince** [comment]
i'd wait to see what the final chart.js 2.0 brings(currently they have have closed all 1.x stuff and are just focusing on that) as i have a feeling overlay will be something that the work they did with rebuilding the scale can handle out of the box.
