### ISSUE TITLE
ScaleOverride not working

### ISSUE THREAD

**Issue by ardav** [leighquince/Chart.js#15]
I want to use these options along with labelsFilter function.

  scaleOverride: true,
    scaleSteps: 4,
    scaleStepWidth: 25,
    scaleStartValue: 0,

But it doesn't work.
your fork: http://jsfiddle.net/mea767ss/117/  labelsfilter works , scaleoverride doesn't
original : http://jsfiddle.net/mea767ss/116/

**Comment by leighquince** [comment]
cheers for the spot, will get a fix out for this as asap

**Comment by ardav** [comment]
Thanks for quick response, can't wait to use this in my project. Labelsfilter is the exact solution I needed.

**Comment by leighquince** [comment]
Quite alright, I was playing around with it anyway as I committed a large change yesterday and was trying out different combinations to see if it broke. Unfortunately for I completely overlooked the scale override as i focused so much on the multiple axis stuff creating their scales correctly I didn't think about when a scale is already provided. Thanks again for the heads up on that, if you notice anything let me know.
