### ISSUE TITLE
Horizontal line missing on responsive

### ISSUE THREAD

**Issue by Bigdragon13th** [leighquince/Chart.js#17]
I got this issue when putting chart in the percentage div. And set responsive to True.

When you resize the browser, the horizontal line will gone missing if the div size is larger than when it's created.

This occurred in Overlay, Line & Bar type (as far as I tested).

Here is the example: http://fiddle.jshell.net/ao0fcwya/

**Comment by leighquince** [comment]
yep will have a look at this and put a fix out, cheers for the spot

**Comment by Bigdragon13th** [comment]
Thanks for the quick reply!

Also I got other issue.
When the chart got data update, the y axis is not update to match the data, and the data will span over the chart if the data is bigger.

Here is the example: http://fiddle.jshell.net/rdaqatng/

**Comment by leighquince** [comment]
Oh just to mention i made a new issue out of your second question, I can see why it is happening but as i now have data over several axis i need to think of a way to make sure the right axis gets updated with the new values when the update is called so.
