### ISSUE TITLE
Possible Mobile problem

### ISSUE THREAD

**Issue by fredericocarneiro** [leighquince/Chart.js#18]
Hi! 
Great job with the bar-line custom script!
I would like to report something that happened to me, but I dont know if it happens only with me.
I've created a bar-line chart e on my laptop with chrome it worked fine.
But I tried open the same chart on my phone Nexus 4 (chrome) but it show the chart.js default charts... but doesnt show the custom bar-line chart.
Could you test on you mobile browser? Thanks.

**Comment by leighquince** [comment]
ill take a look and see what is happening

**Comment by leighquince** [comment]
Actually are you able to provide a fiddle with the described behaviour

**Comment by fredericocarneiro** [comment]
Hi Quince!

I've recreated it in fiddle - https://jsfiddle.net/fredbh/s44mqubt/2/


​


[image: --]
Fred Carneiro
[image: https://]about.me/fredcarneiro
<https://about.me/fredcarneiro?promo=email_sig>

**Comment by leighquince** [comment]
All looks good, i'm using HTC One, Android 4.4.3 with Chrome 46.0.2490.76, do you not see it like this?
![screenshot_2015-11-11-10-01-24](https://cloud.githubusercontent.com/assets/813029/11087543/648853ea-885b-11e5-8ca0-3b1a62e6cbf9.png)

**Comment by fredericocarneiro** [comment]
Weird.
In my nexus 4 don't show, but my wife's phone(LG90)... Its working.
Its not good :(
I will try in other phones.
Em 11/11/2015 03:05, "Leigh Quince" <notifications@github.com> escreveu:

**Comment by leighquince** [comment]
hmmm strange. Are you able to plug the phone into the computer and use the remote debugger to see if there are any error messages in the console. Im not bale to get my hands on a nexus 4 so won't be able to test.

**Comment by fredericocarneiro** [comment]
Nice. I'll try this and let you know :)
Thanks.


[image: --]
Fred Carneiro
[image: https://]about.me/fredcarneiro
<https://about.me/fredcarneiro?promo=email_sig>

**Comment by leighquince** [comment]
One thing i do know is it won't display if you visit the `https` version of the fiddle due to the sources coming from `http`. Saying as a just encase.

**Comment by fredericocarneiro** [comment]
Sorry... In my first try, I couldnt get this remote debug work... I need to
find out how to do this...


[image: --]
Fred Carneiro
[image: https://]about.me/fredcarneiro
<https://about.me/fredcarneiro?promo=email_sig>

**Comment by leighquince** [comment]
Hey did you ever get to the bottom of this?
