### ISSUE TITLE
scaleShowLines not working

### ISSUE THREAD

**Issue by spankrrules** [leighquince/Chart.js#5]
scaleShowVerticalLines: false,
scaleShowHorizontalLines: false

are not working, stil shows lines

**Comment by leighquince** [comment]
yeah this is a new feature i think form the original, i am in the process of rebasing my fork with the latest features, i have another branch with the rebase in i'm just going through and testing at the moment if everything looks good i will merge into master this weekend. I think i remember seeing this feature in there.

**Comment by leighquince** [comment]
all good now, the master on this fork now includes a merge from latest master on nnick/Chart.js
