### ISSUE TITLE
Enabling tooltip when hovering over labels.

### ISSUE THREAD

**Issue by norbiu** [leighquince/Chart.js#6]
Another great addition would be the option to show tooltips when hovering over the horizontal labels in bar charts. Currently the tooltip only shows up when you hover over the bar.

This is especially useful in situations where the value differences are so high that the small bar is barely showing or when the bars are really thin.

**Comment by leighquince** [comment]
oh i like that idea

**Comment by leighquince** [comment]
its odd this is the normal behavior for a line chart but not for a bar chart, im going to add this in as default rather than an option as it doesn't really make sense for the two to operate differently. cheers for highlighting

**Comment by leighquince** [comment]
ok this is now the norm as i feel it should be

**Comment by norbiu** [comment]
It's working great. Thanks!
