### ISSUE TITLE
labelsFilter no longer seems to work

### ISSUE THREAD

**Issue by sebduggan** [leighquince/Chart.js#9]
I've just updated from beta4, and my labelsFilter no longer seems to work.

Looking at the example on jsfiddle, that doesn't seem to be filtering either...

**Comment by leighquince** [comment]
ah yeah i've messed it up when i was merging I think. Sorry about that, will get a fix back in as soon as possible, cheers

**Comment by leighquince** [comment]
yeah i missed that when i merged the latest commits from original chartjs repo. Cheers for spotting i've added it back in now and added a new build for Chart.js,
